- 👋 Hi, I’m @hiiaminoo
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...

<!---
hiiaminoo/hiiaminoo is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
https://raw.githubusercontent.com/not-weuz/Lua/main/kocmoc.lua
